config/routes.rb
Rails.application.routes.draw do
  resources :organizadors
  resources :modalidades
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  has_one :estado
  has_many :organizadors
  
  validates :nome, :estado_id, presence: true
end

app/models/estado.rb
class Estado < ApplicationRecord
  has_many :cidades
  validates :nome, :sigla, presence: true, uniqueness: true
end

app/models/modalidade.rb
class Modalidade < ApplicationRecord
  validates :nome, presence: true, uniqueness: true
end

app/models/organizador.rb
class Organizador < ApplicationRecord
  belongs_to :cidade

  validates :nome, :email, :cidade_id, :telefone, presence: true
  validates :email, :telefone, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :telefone, format: { with: /\A\d{2}9\d{8}\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/modalidades_controller.rb
class ModalidadesController < ApplicationController
  before_action :set_modalidade, only: %i[ show edit update destroy ]

  # GET /modalidades or /modalidades.json
  def index
    @modalidades = Modalidade.all
  end

  # GET /modalidades/1 or /modalidades/1.json
  def show
  end

  # GET /modalidades/new
  def new
    @modalidade = Modalidade.new
  end

  # GET /modalidades/1/edit
  def edit
  end

  # POST /modalidades or /modalidades.json
  def create
    @modalidade = Modalidade.new(modalidade_params)

    respond_to do |format|
      if @modalidade.save
        format.html { redirect_to modalidade_url(@modalidade), notice: "Modalidade was successfully created." }
        format.json { render :show, status: :created, location: @modalidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modalidades/1 or /modalidades/1.json
  def update
    respond_to do |format|
      if @modalidade.update(modalidade_params)
        format.html { redirect_to modalidade_url(@modalidade), notice: "Modalidade was successfully updated." }
        format.json { render :show, status: :ok, location: @modalidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modalidades/1 or /modalidades/1.json
  def destroy
    @modalidade.destroy!

    respond_to do |format|
      format.html { redirect_to modalidades_url, notice: "Modalidade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modalidade
      @modalidade = Modalidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def modalidade_params
      params.require(:modalidade).permit(:nome)
    end
end

app/controllers/organizadors_controller.rb
class OrganizadorsController < ApplicationController
  before_action :set_organizador, only: %i[ show edit update destroy ]

  # GET /organizadors or /organizadors.json
  def index
    @organizadors = Organizador.all
  end

  # GET /organizadors/1 or /organizadors/1.json
  def show
  end

  # GET /organizadors/new
  def new
    @organizador = Organizador.new
  end

  # GET /organizadors/1/edit
  def edit
  end

  # POST /organizadors or /organizadors.json
  def create
    @organizador = Organizador.new(organizador_params)

    respond_to do |format|
      if @organizador.save
        format.html { redirect_to organizador_url(@organizador), notice: "Organizador was successfully created." }
        format.json { render :show, status: :created, location: @organizador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organizador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizadors/1 or /organizadors/1.json
  def update
    respond_to do |format|
      if @organizador.update(organizador_params)
        format.html { redirect_to organizador_url(@organizador), notice: "Organizador was successfully updated." }
        format.json { render :show, status: :ok, location: @organizador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organizador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizadors/1 or /organizadors/1.json
  def destroy
    @organizador.destroy!

    respond_to do |format|
      format.html { redirect_to organizadors_url, notice: "Organizador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organizador
      @organizador = Organizador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organizador_params
      params.require(:organizador).permit(:nome, :email, :telefone, :cidade_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/modalidade_helper.rb
module ModalidadeHelper
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/helpers/organizadors_helper.rb
module OrganizadorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrilhaoDaOnca</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/modalidades/_form.html.erb
<%= form_with(model: modalidade) do |form| %>
  <% if modalidade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(modalidade.errors.count, "error") %> prohibited this modalidade from being saved:</h2>

      <ul>
        <% modalidade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/modalidades/_modalidade.html.erb
<div id="<%= dom_id modalidade %>">
  <p>
    <strong>Nome:</strong>
    <%= modalidade.nome %>
  </p>

</div>

app/views/modalidades/edit.html.erb
<h1>Editing modalidade</h1>

<%= render "form", modalidade: @modalidade %>

<br>

<div>
  <%= link_to "Show this modalidade", @modalidade %> |
  <%= link_to "Back to modalidades", modalidades_path %>
</div>

app/views/modalidades/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Modalidades</h1>

<div id="modalidades">
  <% @modalidades.each do |modalidade| %>
    <%= render modalidade %>
    <p>
      <%= link_to "Show this modalidade", modalidade %>
    </p>
  <% end %>
</div>

<%= link_to "New modalidade", new_modalidade_path %>

app/views/modalidades/new.html.erb
<h1>New modalidade</h1>

<%= render "form", modalidade: @modalidade %>

<br>

<div>
  <%= link_to "Back to modalidades", modalidades_path %>
</div>

app/views/modalidades/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @modalidade %>

<div>
  <%= link_to "Edit this modalidade", edit_modalidade_path(@modalidade) %> |
  <%= link_to "Back to modalidades", modalidades_path %>

  <%= button_to "Destroy this modalidade", @modalidade, method: :delete %>
</div>

app/views/organizadors/_form.html.erb
<%= form_with(model: organizador) do |form| %>
  <% if organizador.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(organizador.errors.count, "error") %> prohibited this organizador from being saved:</h2>

      <ul>
        <% organizador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :cidade_id, style: "display: block" %>
    <%= form.text_field :cidade_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/organizadors/_organizador.html.erb
<div id="<%= dom_id organizador %>">
  <p>
    <strong>Nome:</strong>
    <%= organizador.nome %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= organizador.email %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= organizador.telefone %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= organizador.cidade_id %>
  </p>

</div>

app/views/organizadors/edit.html.erb
<h1>Editing organizador</h1>

<%= render "form", organizador: @organizador %>

<br>

<div>
  <%= link_to "Show this organizador", @organizador %> |
  <%= link_to "Back to organizadors", organizadors_path %>
</div>

app/views/organizadors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Organizadors</h1>

<div id="organizadors">
  <% @organizadors.each do |organizador| %>
    <%= render organizador %>
    <p>
      <%= link_to "Show this organizador", organizador %>
    </p>
  <% end %>
</div>
<button class="btn btn-primary" type="submit">Button</button>
<%= link_to "New organizador", new_organizador_path %>

app/views/organizadors/new.html.erb
<h1>New organizador</h1>

<%= render "form", organizador: @organizador %>

<br>

<div>
  <%= link_to "Back to organizadors", organizadors_path %>
</div>

app/views/organizadors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @organizador %>

<div>
  <%= link_to "Edit this organizador", edit_organizador_path(@organizador) %> |
  <%= link_to "Back to organizadors", organizadors_path %>

  <%= button_to "Destroy this organizador", @organizador, method: :delete %>
</div>